const ACTION_TYPES = {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_SUCCESS: 'AUTH_SUCCESS',

  SELECT_CHAT_ACTION: 'SELECT_CHAT_ACTION',

  LOAD_CHATS_REQUEST: 'LOAD_CHAT_LIST_REQUEST',
  LOAD_CHATS_SUCCESS: 'LOAD_CHAT_LIST_SUCCESS',
  LOAD_CHATS_ERROR: 'LOAD_CHAT_LIST_ERROR',

  CREATE_CHAT_REQUEST: 'CREATE_CHAT_REQUEST',
  CREATE_CHAT_SUCCESS: 'CREATE_CHAT_SUCCESS',
  CREATE_CHAT_ERROR: 'CREATE_CHAT_ERROR',

  LOAD_CHAT_MESSAGES_REQUEST: 'LOAD_CHAT_MESSAGES_REQUEST',
  LOAD_CHAT_MESSAGES_SUCCESS: 'LOAD_CHAT_MESSAGES_SUCCESS',
  LOAD_CHAT_MESSAGES_ERROR: 'LOAD_CHAT_MESSAGES_ERROR',

};

export default ACTION_TYPES;